-- Task 1 - world
-- Q1: Missing letter in 1st position of Country.code
WITH letters AS (
  SELECT 'A' AS l UNION ALL SELECT 'B' UNION ALL SELECT 'C' UNION ALL SELECT 'D' UNION ALL SELECT 'E'
  UNION ALL SELECT 'F' UNION ALL SELECT 'G' UNION ALL SELECT 'H' UNION ALL SELECT 'I' UNION ALL SELECT 'J'
  UNION ALL SELECT 'K' UNION ALL SELECT 'L' UNION ALL SELECT 'M' UNION ALL SELECT 'N' UNION ALL SELECT 'O'
  UNION ALL SELECT 'P' UNION ALL SELECT 'Q' UNION ALL SELECT 'R' UNION ALL SELECT 'S' UNION ALL SELECT 'T'
  UNION ALL SELECT 'U' UNION ALL SELECT 'V' UNION ALL SELECT 'W' UNION ALL SELECT 'X' UNION ALL SELECT 'Y'
  UNION ALL SELECT 'Z'
),
used AS (
  SELECT DISTINCT SUBSTRING(code, 1, 1) AS l
  FROM Country
  WHERE code IS NOT NULL AND LENGTH(code) = 3
)
SELECT letters.l AS missing_letter
FROM letters
LEFT JOIN used ON used.l = letters.l
WHERE used.l IS NULL
ORDER BY letters.l;

-- Q2: Missing letter in 2nd position
WITH letters AS (
  SELECT 'A' AS l UNION ALL SELECT 'B' UNION ALL SELECT 'C' UNION ALL SELECT 'D' UNION ALL SELECT 'E'
  UNION ALL SELECT 'F' UNION ALL SELECT 'G' UNION ALL SELECT 'H' UNION ALL SELECT 'I' UNION ALL SELECT 'J'
  UNION ALL SELECT 'K' UNION ALL SELECT 'L' UNION ALL SELECT 'M' UNION ALL SELECT 'N' UNION ALL SELECT 'O'
  UNION ALL SELECT 'P' UNION ALL SELECT 'Q' UNION ALL SELECT 'R' UNION ALL SELECT 'S' UNION ALL SELECT 'T'
  UNION ALL SELECT 'U' UNION ALL SELECT 'V' UNION ALL SELECT 'W' UNION ALL SELECT 'X' UNION ALL SELECT 'Y'
  UNION ALL SELECT 'Z'
),
used AS (
  SELECT DISTINCT SUBSTRING(code, 2, 1) AS l
  FROM Country
  WHERE code IS NOT NULL AND LENGTH(code) = 3
)
SELECT letters.l AS missing_letter
FROM letters
LEFT JOIN used ON used.l = letters.l
WHERE used.l IS NULL
ORDER BY letters.l;

-- Q3: Missing letter in 3rd position
WITH letters AS (
  SELECT 'A' AS l UNION ALL SELECT 'B' UNION ALL SELECT 'C' UNION ALL SELECT 'D' UNION ALL SELECT 'E'
  UNION ALL SELECT 'F' UNION ALL SELECT 'G' UNION ALL SELECT 'H' UNION ALL SELECT 'I' UNION ALL SELECT 'J'
  UNION ALL SELECT 'K' UNION ALL SELECT 'L' UNION ALL SELECT 'M' UNION ALL SELECT 'N' UNION ALL SELECT 'O'
  UNION ALL SELECT 'P' UNION ALL SELECT 'Q' UNION ALL SELECT 'R' UNION ALL SELECT 'S' UNION ALL SELECT 'T'
  UNION ALL SELECT 'U' UNION ALL SELECT 'V' UNION ALL SELECT 'W' UNION ALL SELECT 'X' UNION ALL SELECT 'Y'
  UNION ALL SELECT 'Z'
),
used AS (
  SELECT DISTINCT SUBSTRING(code, 3, 1) AS l
  FROM Country
  WHERE code IS NOT NULL AND LENGTH(code) = 3
)
SELECT letters.l AS missing_letter
FROM letters
LEFT JOIN used ON used.l = letters.l
WHERE used.l IS NULL
ORDER BY letters.l;
